[package]
name = "gen-preconf-tx"
version = "0.1.0"
edition = "2021"

[dependencies]
eyre = "0.6.12"
tokio = { version = "1.41.1", features = ["full"] }
alloy = { version = "0.6.4", features = ["full", "node-bindings", "rlp"] }
hex = "0.4.3"
